branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

language: swift

stages:
  - Tests
  - Compatibility

jobs:
  include:
#    - stage: Tests
#      os: linux
#      dist: trusty
#      name: macOS Tests
#      script: swift test
    - stage: Tests
      os: osx
      osx_image: xcode11.4
      name: Unit Tests
      script: fastlane ios tests
    - stage: Compatibility
      os: osx
      osx_image: xcode11.4
      name: DependencyManager compatibility
      script: fastlane ios compatibilityTests
